__title__ = 'ltcli'
__description__ = 'Command line tool for LightningDB'
__url__ = 'https://lightningdb.io/'
__version__ = '1.1.0b4'
__author__ = 'LightningDB'
__email__ = 'lightningdb@sktelecom.com'
